baseUrl = "https://peterevans.dev/"
languageCode = "en-us"
title = "The blog of Peter Evans"
theme = "vela"
disableKinds = ["taxonomy"]
enableEmoji = true
pygmentsCodeFences = true
pygmentsUseClasses = true
canonifyURLs = true
rssLimit = 20

[params]
    author = "Peter Evans"
    description = "Thoughts and notes on software engineering, architecture and testing."
    keywords = ["Peter Evans", "software engineering", "software architecture", "software testing"]

[markup.goldmark.renderer]
unsafe = true
